### ISSUE TITLE
Add travis.yml config

### ISSUE THREAD

**Issue by joshghent** [joshghent/password#20]
Add a travis yml config to run our test suite against the latest version of node, and all LTS editions

**Comment by sladyn98** [comment]
@joshghent i would like to take this issue how do i go about it

**Comment by joshghent** [comment]
@sladyn98 Check out the travis yml [here](https://github.com/joshghent/deepClone/blob/master/.travis.yml) - they should be very similar. Also check out the travis CI docs for more [info](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) 👍

**Comment by joshghent** [comment]
Fixed in #22 - thanks @sladyn98
