### ISSUE TITLE
Recreate the site in React

### ISSUE THREAD

**Issue by joshghent** [joshghent/password#21]
Attempt to recreate the site in react using the existing design. In light of discussions in #19, we also need a way of handling configuration for the frontend. Make these configurable in a dotenv file.

**Comment by bpod** [comment]
I can bang this out in react if no one has taken it already. 💯
Also, looks like the demo is down, if I clone this should it run and work locally?

**Comment by joshghent** [comment]
@bpod All yours my friend. Yeah it won't be down, just takes a while to load for some reason. It's hosted via now.sh. Not been too happy with the performance compared to Heroku. Try it now!
Would be great if you could rewrite and configure the now deployment step too 👍

**Comment by bpod** [comment]
👍Cool! I'll get something together tonight/tomorrow and follow up. 🍻

**Comment by joshghent** [comment]
@bpod Awesome, look forward to it. No rush! 🍺

**Comment by bpod** [comment]
@joshghent I noticed the link in the readme is broken too and I have a fix/PR for that ready too.. can you open up access to me so that I can create a PR? Thanks.

**Comment by joshghent** [comment]
@bpod Good spot, thanks for that! How is the react rewrite going? Try to fork the repo then create a PR from that repo, that is the best way to manage it 👍 If you would like to maintain this project on an on going basis (as I do not have the time) then let me know and I will add you so you can deploy and make PR's directly etc.

**Comment by bpod** [comment]
@joshghent Sounds great. It's going well, just need to get past a couple hurdles with building locally. I'd be happy to help maintain. 👍

**Comment by bpod** [comment]
@joshghent How do you feel about blowing all the server stuff away and starting over (I may be able to save some of it) ?

**Comment by joshghent** [comment]
@bpod Go for it! Would be great to break this up and make it proper. What do you reckon?

**Comment by joshghent** [comment]
@bpod I've changed the issue to WIP. Go wild man! Would love to see your work! 👍 
Yes please do, that would be the best, we can then both work on it

**Comment by bpod** [comment]
@joshghent [](https://media.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

**Comment by joshghent** [comment]
@bpod I've added you to the repo, you can take charge with maintaining this 👍 Perhaps we can create a bit of a roadmap to improving this project

**Comment by bpod** [comment]
@joshghent Awesome... thank you. Yea, roadmap is a great plan. These are a couple I was thinking for the time being..

- Get a version built wit React working alongside existing project (Redux? Might be overkill at fist but could be nice)
- Evaluate current server impl
    - Either keep/update current version or Roll a new impl
- Add proper documentation (README - CONTRIBUTING - etc)
- Figure out best place to host demo

**Comment by joshghent** [comment]
@bpod Sounds good, going after the React site first is the best call then we can add more features and stuff like that 👍

**Comment by bpod** [comment]
@joshghent 

I got the UI built out and wired up to Redux state. Added some routing in case we want an `About` page or credits or something. Also created a `Toast` component for feedback (i.e. copied to clipboard, etc)

I can speak more to the tech stack when this port is closer to being complete, but it's pretty modern and awesome.

I Just need to get it actually generating passwords now.....
😎🎉:shipit: 

Massive PR coming soon. 🤓 

<img width="1186" alt="screen shot 2018-10-05 at 1 21 30 am" src="https://user-images.githubusercontent.com/30637419/46519189-17a43d80-c83d-11e8-9738-f7a45a137c8d.png">

**Comment by joshghent** [comment]
@bpod The interface looks awesome man, nice job! This is really cool! So excited for this :+1: Nice work! You've worked hard on this
We will have to write some interface tests and stuff perhaps in the future :+1:

**Comment by bpod** [comment]
Thanks man! Just an FYI... 
I've been busy on-boarding for a new project but I'm hoping to wrap this up late this week/weekend. Stay tuned!! 😎

**Comment by joshghent** [comment]
@bpod No rush dude! Thanks a lot for continuing to work on this! It's great 👍

**Comment by bpod** [comment]
@joshghent Hey Man!!!! Happy New Year!!! I hope you had a great holiday season and things are going well. 

Sorry for the delay... We had another baby and I took a bunch of PTO time around the holidays! I'm back in action now though, and would like to pick things back up and get a new release out!!! I'll be in touch soon and have some more updates. 🍻

**Comment by joshghent** [comment]
@bpod Hey, yes had a great holiday. Hope you did too! Sounds like you've been very busy! Congratulations on the new baby! Boy or girl? 👶 🥂 
Ok perfect, take your time! Be with your family, this can wait 👍 But if you did any work on it then it would be more than welcome.
