### ISSUE TITLE
Create 'About Route'

### ISSUE THREAD

**Issue by bpod** [joshghent/password#30]
- [X] Create route, 'About' duckling, style support
- [X] Include XKCD image
- [x] Include link to XKCD original comic
- [x] Include Disclaimers
- [x] Include link to GITHUB Repo
- [x] Include link(s) to contributors?

**Comment by joshghent** [comment]
@bpod Good thinking here! That's a great idea. Definitely can get this in for the react port. Happy for you to do this if you like!

**Comment by bpod** [comment]
@joshghent I actually already have a branch ready for it. :P I'll have something ready to look at shortly. 

I'm planning on removing all of the server implementation and handling any routing with React-Router. With the way this is set up, the only thing a server is going to need to do is serve the static HTML page and bundled js. So it could be deployed anywhere that can serve that up.

**Comment by joshghent** [comment]
@bpod Nice dude! I'd be very much in favor of React router, was pretty easy to setup when I tried it out. Nice work 👍

**Comment by bpod** [comment]
<img width="1027" alt="screen shot 2019-02-12 at 10 51 24 am" src="https://user-images.githubusercontent.com/30637419/52652741-4948a780-2eb4-11e9-80f6-1b52013e85a5.png">
