### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by bpod** [joshghent/password#31]
Review README and any other docs before cutting new release.

Include
- [X] Explanation of Ducks pattern
- [X] Explanation of GIT Flow pattern
- ~[ ] How to write, un tests, etc.~ Still need TODO.. will create a new issue
- [X] Explanation of Emotion.js and CSS in JS as a pattern

**Comment by joshghent** [comment]
Great idea, README is the backbone of any great project, so important that we nail this! 👍

**Comment by bpod** [comment]
Closed by #36

**Comment by bpod** [comment]
Closed by #36
